### ISSUE TITLE
`checkMode auto` skips some children when checking an item while its not opened

### ISSUE THREAD

**Issue by robertklep** [N00ts/vue3-treeview#11]
The issue can be demonstrated with one of your demo's: https://codesandbox.io/s/confogiration-umz56

Enable "Checkboxes" and "Checkmode auto", make sure the `text1` node is closed, then check it.

When you open it, you'll see that the first nodes of `text11` and `text13` will not be checked:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/1190916/159131598-8da8ecdc-dbde-448a-ad31-17f3df9de3c4.png">

This behaviour is consistent, I noticed it when trying to implement a tree view for my own project.

When `text1` is opened, _then_ checked, everything works.

**EDIT**: a related issue: when you close `text1` and reopen it, `text11` and `text13` will be in an unchecked state (so not indeterminate anymore):

<img width="162" alt="image" src="https://user-images.githubusercontent.com/1190916/159153168-561a950c-7661-4da4-a64d-8b989829880b.png">

**Comment by robertklep** [comment]
Looks like there's a race condition between [`recurseDown`](https://github.com/N00ts/vue3-treeview/blob/36d8a9c48420b9803628aea2dfc4c27026c40876/src/setup/checkbox/auto.ts#L67) and the watchers in [`useCheckBox`](https://github.com/N00ts/vue3-treeview/blob/master/src/setup/useCheckBox.ts).

I managed to fix this particular issue by using post flushing on the watchers, but this introduces other issues :(

**Comment by N00ts** [comment]
If you find the issue, don't hesitate to fix it. I will try to take a look but unfortunately I am very busy right now

**Comment by N00ts** [comment]
I just published a new version (0.3.6) that should fix the issue. You can update the demo :)

**Comment by robertklep** [comment]
@N00ts sadly, this introduces an issue that I also ran into (and haven't been able to fix yet).

Steps to show the issue:
* enable "Checkboxes" and "Checkmode auto"
* check "text1"
* open "text1" (which shows the initial issue is now fixed)
* open "text11"
* uncheck "id111"

The state will look like this:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/1190916/160889118-561d5bc7-6ff1-4c83-b934-ebd6c30c1687.png">

Then:
* close "text1"
* open "text1" again

The state now looks like this:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/1190916/160888675-522724fb-318e-44e5-83b1-4277c1158980.png">

So "text11" should have been indeterminate but by closing "text1" it went to "unchecked", as are its children.

**Comment by N00ts** [comment]
Thank you for the feedback it should be fixed with version 0.3.7 :)

**Comment by robertklep** [comment]
Awesome! I haven't tested extensively yet but it looks like it works as expected now 🥳
