### ISSUE TITLE
Bug: method "insertIn" doesn't care if we drop node into another node which is in leaves array in config

### ISSUE THREAD

**Issue by olsoncarsen** [N00ts/vue3-treeview#14]
If we want to use drag and drop while async loading and there are some nodes without children, we put their ids into the leaves array in config. If we drag and drop into the node which is in leaves array, icon will not show and node id won't be removed from leaves array.
Way to reproduce: drag node into the "text3" or "text4".
Sandbox: https://codesandbox.io/s/async-forked-qq3mii?file=/src/App.vue

**Comment by olsoncarsen** [comment]
![Screenshot 2022-04-07 at 9 44 36 PM](https://user-images.githubusercontent.com/71249036/162274705-363e54f5-4669-4a8f-aa4d-4df7887a9f91.png)

**Comment by N00ts** [comment]
Hello, i'm sorry i'm very busy right now, I will take a look as soon as I can.

**Comment by olsoncarsen** [comment]
It's alright

**Comment by N00ts** [comment]
Hey I wanted to have a look but I feel that your example is not working anymore can you create a new test case please :) ?

**Comment by olsoncarsen** [comment]
https://codesandbox.io/s/async-forked-qq3mii?file=/src/App.vue

**Comment by olsoncarsen** [comment]
@N00ts this should work, steps to reproduce: drag task3 into task4

**Comment by N00ts** [comment]
Hello, what you try to do is to handle "leaves" manually. The icon does not appear because you keep the id the drop target node in config.leaves. I modifed the project and put "node-drop" after insert event so you can handle it manually in this event.

Regards

**Comment by olsoncarsen** [comment]
@N00ts, okay. I'm closing this issue
