### ISSUE TITLE
chore: maybe not need lodash dep

### ISSUE THREAD

**Issue by geotify** [N00ts/vue3-treeview#19]
![2022-07-09_101445](https://user-images.githubusercontent.com/97531038/178087904-2ce042d8-a79b-492c-b24b-65e0f15536dd.png)
the lodash only use in line 5704, but the whole lodash build in dist file

**Comment by N00ts** [comment]
Hey I just pushed a new version 0.4 that get only desired lodash libraries and should reduce package size !
