### ISSUE TITLE
not work with vue 3 typescript

### ISSUE THREAD

**Issue by sameerFront** [N00ts/vue3-treeview#23]
i just create vue3 typescript , its like stuck and not working 
![image](https://user-images.githubusercontent.com/113237226/197710892-01dfaffb-31ca-4259-b712-4a09798d9977.png)

and  click (open children) not work
![image](https://user-images.githubusercontent.com/113237226/197711068-a1abc518-900f-415f-8dc1-11f98dd2dff3.png)

**Comment by N00ts** [comment]
Hey, can you provide reproduction env ?

**Comment by sameerFront** [comment]
its in development env not reproduction

**Comment by N00ts** [comment]
If don't see your code how am i supposed to tell you what is wrong ? Can you provide a candesandbox ?

**Comment by N00ts** [comment]
Maybe just declare module in your d.ts file ?
like "declare module 'vue3-treeview';" ?

**Comment by N00ts** [comment]
looks like it is duplicate of [10](https://github.com/N00ts/vue3-treeview/issues/10)
