### ISSUE TITLE
Support double click event

### ISSUE THREAD

**Issue by caveofjulian** [N00ts/vue3-treeview#27]
Hi there! Is it possible to support a on double click event? This way we can for instance "choose" something from the treeview.

**Comment by N00ts** [comment]
What do you mean exactly can you provide precise exemple ?

**Comment by vcavallo** [comment]
With the support of a double-click event, you could, for instance, toggle the open state of a node by double-clicking it (vs just clicking the dropdown icon)

**Comment by N00ts** [comment]
There is already a @dblclick event on span, but if you like you can modify project and propose a pull request. I will have a look :)
