### ISSUE TITLE
Vue version 3.2.25 has issues

### ISSUE THREAD

**Issue by caveofjulian** [N00ts/vue3-treeview#28]
Hello, first of all thanks for your contribution!

Vue version 3.2.25 has an issue for me:
[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 

Upgrading to 3.2.45 works, however, this is not possible for my current project because that breaks reactivity in another library.
Would you have any idea what this error means?

**Comment by N00ts** [comment]
Hey, can you provide reproduction exemple (codesandbox or other) ?
