### ISSUE TITLE
Programatically set focused node

### ISSUE THREAD

**Issue by muzicaed** [N00ts/vue3-treeview#36]
Hi!

Thanks for a really nice library!
I have a use case that I think is not covered with the current implementation. 

I use this component to display a folder structure in my project. The idea is that the user should use the tree to select a parent for an item. This works perfectly when creating a new item by using the `node-focus` event to see what node was selected. 

But, when the user wants to edit an item in my application, I see no way to programatically select a node in the tree. Ie. I have the selected id from database and I want to display the tree with that particular node pre-selected in the tree.
 
Im not sure if there currently is a way to do this that Im not seeing or if this might be a missing feature?

**Comment by muzicaed** [comment]
I found a way using the check boxes. When checking a box I just programatically unchecked last checked and thereby forcing a "singel selection". This was actually better, as the focus was removed when eg. clicking on another field etc.

**Comment by d33p-dev** [comment]
Can we reopen this or should I post a new issue?  I have same question.  How do I programmatically select a node?  I'm doing a scene edit in my main app UI and as items in the scene (canvas view) are selected, I need to keep the tree in sync.  How do we do this?

Not sure the unselect all is needed...  But, I (incorrectly and inadvertently) added a "selected" property to the node's state by running this code...  There is no "selected" state for a node according to the docs.

How can we select a node?

        SelectNode(id) {
            // Clear all selections
            Object.keys(this.nodes).forEach(nodeId => {
                this.nodes[nodeId].state.selected = false;
            });
            
            // Select target node
            if (this.nodes[id]) {
                this.nodes[id].state.selected = true;
                this.selectedNodeId = id;
            }
        },
