### ISSUE TITLE
Leaf icon

### ISSUE THREAD

**Issue by laurentleb-comnum** [N00ts/vue3-treeview#44]
Hi, 
Amazing job, so simple but nice. 

I would like to draw an icon on some nodes, roots, nodes or leafs. Is it possible to do it ? Should I simply use the slots before the text ?

**Comment by DeivisFelipe** [comment]
i really want this feature

**Comment by DanilRusakov** [comment]
I think [this solution](https://github.com/N00ts/vue3-treeview/issues/9) can help for now

**Comment by N00ts** [comment]
please read documentation before ask questions
https://n00ts.github.io/vue3-treeview/guide/properties.html#icons
