### ISSUE TITLE
Custom icons per node

### ISSUE THREAD

**Issue by TechSupportJosh** [N00ts/vue3-treeview#9]
Hi there,

Is it possible to define an icon for a specific node? For example, if you're attempting to represent a file structure:

![image](https://user-images.githubusercontent.com/5190840/146062624-73c4f393-4ff1-4176-92ed-e438c5fa68bc.png)

It would be nice to be able to override the "fakeIcon" inside TreeIcons.vue for something like this:

![image](https://user-images.githubusercontent.com/5190840/146062867-ca637373-6066-47c3-b818-665b5d917073.png)

An example from codepen, where each file extension has a different icon:

![image](https://user-images.githubusercontent.com/5190840/146062921-e215b53e-c47a-403c-ae7a-4ae30a90af87.png)

Thank you!

**Comment by N00ts** [comment]
Hello, what is your use case ? Maybe you can use the slots to achieve this. If it does not fit you can customize open / close icon for each node.

**Comment by TechSupportJosh** [comment]
Slots worked perfectly well, thank you! Is it possible to make the slots (or the entire node) clickable, rather than just the icon?

**Comment by N00ts** [comment]
You can do what you want with the slots. For example, you can @click.stop to avoid propagation to parent.
Here is an [example](https://codesandbox.io/s/slots-with-class-vsd4n?file=/src/App.vue) for what you want to achieve (maybe reload needed)
